version: '3.2'

networks:
    fabcar_net:
        external: 
            name: fabcar_net

services:

    ca_org2:
        networks:
            fabcar_net:
                aliases:
                    - .org2.example.com
                    - ca_org2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == lab
        image: hyperledger/fabric-ca:$CAIMAGE_TAG
        hostname: .org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=.org2.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d8737f3a1cf3dcfa359455aeacbe106b9707f6609debcd685d32f756f4017acf_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d8737f3a1cf3dcfa359455aeacbe106b9707f6609debcd685d32f756f4017acf_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == lab
        image: hyperledger/fabric-couchdb:$DBIMAGE_TAG
        hostname: couchdb0_org2
        networks:
           - fabcar_net

    couchdb1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == lab
        image: hyperledger/fabric-couchdb:$DBIMAGE_TAG
        hostname: couchdb1_org2
        networks:
           - fabcar_net